### ISSUE TITLE
Delete this github?

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Conky#3]

**Comment by Dobbie03** [comment]
Where has conky been placed?

**Comment by erikdubois** [comment]
on other github

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Dobbie03** [comment]
Delete this one then.

**Comment by erikdubois** [comment]
https://github.com/ARCHLabs/Archlabs-Conky-New-Syntax

**Comment by erikdubois** [comment]
can you delete it
on ipad

**Comment by Dobbie03** [comment]
Deleting
